---
- hosts: all
  vars:
      http_port: 80
          max_clients: 300
	    remote_user: root
	      tasks:
	        - name: ensure nginx is at the latest version
		    yum:
		          name: nginx
			        state: latest

